services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    volumes:
      - "/app/frontend/node_modules"
      - "./frontend/src:/app/frontend/src"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGODB_URI=${URI}
      - MONGODB_DATABASE=${dbName}
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules/
    depends_on:
      - db
    links:
      - db

  db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${dbUser}
      MONGO_INITDB_ROOT_PASSWORD: ${dbPass}
      MONGO_INITDB_DATABASE: ${dbName}
    ports:
      - 27017:27017
 