services:
  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    volumes:
      - "/app/frontend/node_modules"
      - "./frontend/src:/app/frontend/src"
 